# Generated by Django 6.0.4 on 2026-05-03 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji', max_length=10)),
                ('required_xp', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Бейдж',
                'verbose_name_plural': 'Бейджи',
                'ordering': ['required_xp'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
            ],
            options={
                'verbose_name': 'Бейдж пользователя',
                'verbose_name_plural': 'Бейджи пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserGameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_points', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('badges', models.ManyToManyField(blank=True, through='gamification.UserBadge', to='gamification.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игровой профиль',
                'verbose_name_plural': 'Игровые профили',
            },
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='gamification.usergameprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user_profile', 'badge')},
        ),
    ]
